# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/bdegreve/bramz-pre-commit-hooks.git
    rev: babbefa12095ed4ee7270715044148bff66d2735
    hooks:
      - id: bramz-fix-copyright
        args: [--author=Bram de Greve, --prefix=Copyright, --license-file=LICENSE]
        exclude: 'conanfile\.py$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9 # keep in sync with dev-constraints.txt
    hooks:
    - id: ruff-format
    - alias: ruff-isort
      name: ruff-isort
      id: ruff
      args: [--select=I, --fix]
    - alias: ruff-check
      name: ruff-check
      id: ruff
